// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app_petition.proto

package lazyledger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PetitionAppTransaction struct {
	// Types that are valid to be assigned to Message:
	//	*PetitionAppTransaction_Apm
	//	*PetitionAppTransaction_Spm
	Message              isPetitionAppTransaction_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *PetitionAppTransaction) Reset()         { *m = PetitionAppTransaction{} }
func (m *PetitionAppTransaction) String() string { return proto.CompactTextString(m) }
func (*PetitionAppTransaction) ProtoMessage()    {}
func (*PetitionAppTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_e792406857c1b4a0, []int{0}
}

func (m *PetitionAppTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PetitionAppTransaction.Unmarshal(m, b)
}
func (m *PetitionAppTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PetitionAppTransaction.Marshal(b, m, deterministic)
}
func (m *PetitionAppTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PetitionAppTransaction.Merge(m, src)
}
func (m *PetitionAppTransaction) XXX_Size() int {
	return xxx_messageInfo_PetitionAppTransaction.Size(m)
}
func (m *PetitionAppTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_PetitionAppTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_PetitionAppTransaction proto.InternalMessageInfo

type isPetitionAppTransaction_Message interface {
	isPetitionAppTransaction_Message()
}

type PetitionAppTransaction_Apm struct {
	Apm *AddPetitionMessage `protobuf:"bytes,1,opt,name=apm,oneof"`
}

type PetitionAppTransaction_Spm struct {
	Spm *SignPetitionMessage `protobuf:"bytes,2,opt,name=spm,oneof"`
}

func (*PetitionAppTransaction_Apm) isPetitionAppTransaction_Message() {}

func (*PetitionAppTransaction_Spm) isPetitionAppTransaction_Message() {}

func (m *PetitionAppTransaction) GetMessage() isPetitionAppTransaction_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PetitionAppTransaction) GetApm() *AddPetitionMessage {
	if x, ok := m.GetMessage().(*PetitionAppTransaction_Apm); ok {
		return x.Apm
	}
	return nil
}

func (m *PetitionAppTransaction) GetSpm() *SignPetitionMessage {
	if x, ok := m.GetMessage().(*PetitionAppTransaction_Spm); ok {
		return x.Spm
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PetitionAppTransaction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PetitionAppTransaction_Apm)(nil),
		(*PetitionAppTransaction_Spm)(nil),
	}
}

type AddPetitionMessage struct {
	Text                 *string  `protobuf:"bytes,1,req,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPetitionMessage) Reset()         { *m = AddPetitionMessage{} }
func (m *AddPetitionMessage) String() string { return proto.CompactTextString(m) }
func (*AddPetitionMessage) ProtoMessage()    {}
func (*AddPetitionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e792406857c1b4a0, []int{1}
}

func (m *AddPetitionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPetitionMessage.Unmarshal(m, b)
}
func (m *AddPetitionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPetitionMessage.Marshal(b, m, deterministic)
}
func (m *AddPetitionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPetitionMessage.Merge(m, src)
}
func (m *AddPetitionMessage) XXX_Size() int {
	return xxx_messageInfo_AddPetitionMessage.Size(m)
}
func (m *AddPetitionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPetitionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AddPetitionMessage proto.InternalMessageInfo

func (m *AddPetitionMessage) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type SignPetitionMessage struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,req,name=signature" json:"signature,omitempty"`
	Signer               []byte   `protobuf:"bytes,3,req,name=signer" json:"signer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignPetitionMessage) Reset()         { *m = SignPetitionMessage{} }
func (m *SignPetitionMessage) String() string { return proto.CompactTextString(m) }
func (*SignPetitionMessage) ProtoMessage()    {}
func (*SignPetitionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e792406857c1b4a0, []int{2}
}

func (m *SignPetitionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignPetitionMessage.Unmarshal(m, b)
}
func (m *SignPetitionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignPetitionMessage.Marshal(b, m, deterministic)
}
func (m *SignPetitionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignPetitionMessage.Merge(m, src)
}
func (m *SignPetitionMessage) XXX_Size() int {
	return xxx_messageInfo_SignPetitionMessage.Size(m)
}
func (m *SignPetitionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignPetitionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignPetitionMessage proto.InternalMessageInfo

func (m *SignPetitionMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SignPetitionMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignPetitionMessage) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

func init() {
	proto.RegisterType((*PetitionAppTransaction)(nil), "lazyledger.PetitionAppTransaction")
	proto.RegisterType((*AddPetitionMessage)(nil), "lazyledger.AddPetitionMessage")
	proto.RegisterType((*SignPetitionMessage)(nil), "lazyledger.SignPetitionMessage")
}

func init() { proto.RegisterFile("app_petition.proto", fileDescriptor_e792406857c1b4a0) }

var fileDescriptor_e792406857c1b4a0 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8c, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xdd, 0xec, 0xa1, 0xec, 0x28, 0x16, 0x23, 0x1c, 0x29, 0x44, 0x97, 0xad, 0x52, 0x6d,
	0x71, 0x3e, 0xc1, 0x59, 0xd9, 0x08, 0x12, 0xed, 0x2c, 0x24, 0x98, 0x21, 0x04, 0x2e, 0xd9, 0x21,
	0x89, 0xa0, 0x3e, 0x83, 0x0f, 0x2d, 0x1b, 0x4f, 0x4e, 0x70, 0xbb, 0xf9, 0xe6, 0xff, 0xbf, 0x1f,
	0xd0, 0x30, 0xbf, 0x30, 0x15, 0x5f, 0xfc, 0x14, 0x47, 0x4e, 0x53, 0x99, 0x10, 0x76, 0xe6, 0xf3,
	0x63, 0x47, 0xd6, 0x51, 0x1a, 0xbe, 0x1a, 0x58, 0x3f, 0xec, 0xe3, 0x2d, 0xf3, 0x53, 0x32, 0x31,
	0x9b, 0xd7, 0x99, 0x70, 0x03, 0xad, 0xe1, 0x20, 0x9b, 0xbe, 0x51, 0xa7, 0x9b, 0xab, 0xf1, 0x20,
	0x8d, 0x5b, 0x6b, 0x7f, 0x9d, 0x7b, 0xca, 0xd9, 0x38, 0xba, 0x3b, 0xd2, 0x73, 0x19, 0x6f, 0xa0,
	0xcd, 0x1c, 0xa4, 0xa8, 0xce, 0xf5, 0x5f, 0xe7, 0xd1, 0xbb, 0xb8, 0x20, 0x65, 0x0e, 0xb7, 0x1d,
	0x9c, 0x84, 0x9f, 0xcf, 0xa0, 0x00, 0xff, 0x8f, 0x23, 0xc2, 0xaa, 0xd0, 0x7b, 0x91, 0x4d, 0x2f,
	0x54, 0xa7, 0xeb, 0x3d, 0x3c, 0xc3, 0xc5, 0xc2, 0x24, 0x9e, 0x83, 0xf0, 0xb6, 0x16, 0x57, 0x5a,
	0x78, 0x8b, 0x97, 0xd0, 0x65, 0xef, 0xa2, 0x29, 0x6f, 0x89, 0xa4, 0xe8, 0x85, 0x3a, 0xd3, 0x87,
	0x07, 0xae, 0xe1, 0x78, 0x06, 0x4a, 0xb2, 0xad, 0xd1, 0x9e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x85, 0x47, 0xe6, 0xf1, 0x36, 0x01, 0x00, 0x00,
}
