// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app_registrar.proto

package lazyledger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterTransaction struct {
	Owner                []byte   `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	Name                 []byte   `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTransaction) Reset()         { *m = RegisterTransaction{} }
func (m *RegisterTransaction) String() string { return proto.CompactTextString(m) }
func (*RegisterTransaction) ProtoMessage()    {}
func (*RegisterTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f106271c15fd48, []int{0}
}

func (m *RegisterTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTransaction.Unmarshal(m, b)
}
func (m *RegisterTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTransaction.Marshal(b, m, deterministic)
}
func (m *RegisterTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTransaction.Merge(m, src)
}
func (m *RegisterTransaction) XXX_Size() int {
	return xxx_messageInfo_RegisterTransaction.Size(m)
}
func (m *RegisterTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTransaction proto.InternalMessageInfo

func (m *RegisterTransaction) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *RegisterTransaction) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RegisterTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RegisterTransactionMessage struct {
	Name                 []byte   `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTransactionMessage) Reset()         { *m = RegisterTransactionMessage{} }
func (m *RegisterTransactionMessage) String() string { return proto.CompactTextString(m) }
func (*RegisterTransactionMessage) ProtoMessage()    {}
func (*RegisterTransactionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f106271c15fd48, []int{1}
}

func (m *RegisterTransactionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTransactionMessage.Unmarshal(m, b)
}
func (m *RegisterTransactionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTransactionMessage.Marshal(b, m, deterministic)
}
func (m *RegisterTransactionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTransactionMessage.Merge(m, src)
}
func (m *RegisterTransactionMessage) XXX_Size() int {
	return xxx_messageInfo_RegisterTransactionMessage.Size(m)
}
func (m *RegisterTransactionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTransactionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTransactionMessage proto.InternalMessageInfo

func (m *RegisterTransactionMessage) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterTransaction)(nil), "lazyledger.RegisterTransaction")
	proto.RegisterType((*RegisterTransactionMessage)(nil), "lazyledger.RegisterTransactionMessage")
}

func init() { proto.RegisterFile("app_registrar.proto", fileDescriptor_84f106271c15fd48) }

var fileDescriptor_84f106271c15fd48 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0x28, 0x88,
	0x2f, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x29, 0x4a, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0xca, 0x49, 0xac, 0xaa, 0xcc, 0x49, 0x4d, 0x49, 0x4f, 0x2d, 0x52, 0x8a, 0xe5, 0x12, 0x0e,
	0x02, 0x4b, 0xa7, 0x16, 0x85, 0x14, 0x25, 0xe6, 0x15, 0x27, 0x26, 0x97, 0x64, 0xe6, 0xe7, 0x09,
	0x89, 0x70, 0xb1, 0xe6, 0x97, 0xe7, 0xa5, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x69, 0xf0, 0x04, 0x41,
	0x38, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x41, 0x30, 0x5b, 0x48,
	0x86, 0x8b, 0xb3, 0x38, 0x33, 0x3d, 0x2f, 0xb1, 0xa4, 0xb4, 0x28, 0x55, 0x82, 0x19, 0x2c, 0x81,
	0x10, 0x50, 0x32, 0xe0, 0x92, 0xc2, 0x62, 0xbc, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x2a, 0xdc,
	0x3c, 0x46, 0x84, 0x79, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0xb6, 0x18, 0xac, 0xb2, 0x00,
	0x00, 0x00,
}
