// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app_currency.proto

package lazyledger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CurrencyTransaction struct {
	To                   []byte   `protobuf:"bytes,1,req,name=to" json:"to,omitempty"`
	From                 []byte   `protobuf:"bytes,2,req,name=from" json:"from,omitempty"`
	Amount               *uint64  `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,req,name=signature" json:"signature,omitempty"`
	Dependency           []byte   `protobuf:"bytes,5,opt,name=dependency" json:"dependency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyTransaction) Reset()         { *m = CurrencyTransaction{} }
func (m *CurrencyTransaction) String() string { return proto.CompactTextString(m) }
func (*CurrencyTransaction) ProtoMessage()    {}
func (*CurrencyTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_616dce597ab00d2c, []int{0}
}

func (m *CurrencyTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyTransaction.Unmarshal(m, b)
}
func (m *CurrencyTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyTransaction.Marshal(b, m, deterministic)
}
func (m *CurrencyTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyTransaction.Merge(m, src)
}
func (m *CurrencyTransaction) XXX_Size() int {
	return xxx_messageInfo_CurrencyTransaction.Size(m)
}
func (m *CurrencyTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyTransaction proto.InternalMessageInfo

func (m *CurrencyTransaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *CurrencyTransaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *CurrencyTransaction) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *CurrencyTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *CurrencyTransaction) GetDependency() []byte {
	if m != nil {
		return m.Dependency
	}
	return nil
}

type CurrencyTransactionMessage struct {
	To                   []byte   `protobuf:"bytes,1,req,name=to" json:"to,omitempty"`
	Amount               *uint64  `protobuf:"varint,2,req,name=amount" json:"amount,omitempty"`
	Dependency           []byte   `protobuf:"bytes,3,opt,name=dependency" json:"dependency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyTransactionMessage) Reset()         { *m = CurrencyTransactionMessage{} }
func (m *CurrencyTransactionMessage) String() string { return proto.CompactTextString(m) }
func (*CurrencyTransactionMessage) ProtoMessage()    {}
func (*CurrencyTransactionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_616dce597ab00d2c, []int{1}
}

func (m *CurrencyTransactionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyTransactionMessage.Unmarshal(m, b)
}
func (m *CurrencyTransactionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyTransactionMessage.Marshal(b, m, deterministic)
}
func (m *CurrencyTransactionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyTransactionMessage.Merge(m, src)
}
func (m *CurrencyTransactionMessage) XXX_Size() int {
	return xxx_messageInfo_CurrencyTransactionMessage.Size(m)
}
func (m *CurrencyTransactionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyTransactionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyTransactionMessage proto.InternalMessageInfo

func (m *CurrencyTransactionMessage) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *CurrencyTransactionMessage) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *CurrencyTransactionMessage) GetDependency() []byte {
	if m != nil {
		return m.Dependency
	}
	return nil
}

func init() {
	proto.RegisterType((*CurrencyTransaction)(nil), "lazyledger.CurrencyTransaction")
	proto.RegisterType((*CurrencyTransactionMessage)(nil), "lazyledger.CurrencyTransactionMessage")
}

func init() { proto.RegisterFile("app_currency.proto", fileDescriptor_616dce597ab00d2c) }

var fileDescriptor_616dce597ab00d2c = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xc1, 0xca, 0x82, 0x40,
	0x10, 0x80, 0x71, 0xf5, 0xff, 0xa1, 0x41, 0x3a, 0x4c, 0x10, 0x4b, 0x44, 0x88, 0x27, 0x4f, 0xbd,
	0x44, 0xe7, 0x2e, 0xd2, 0x3d, 0x16, 0x77, 0x12, 0x41, 0x77, 0x97, 0xd9, 0xf5, 0x60, 0x2f, 0xd1,
	0x2b, 0x47, 0x22, 0x98, 0xd5, 0x6d, 0xe6, 0x1b, 0x86, 0xef, 0x03, 0x54, 0xce, 0x5d, 0xab, 0x9e,
	0x99, 0x4c, 0x35, 0x1c, 0x1d, 0xdb, 0x60, 0x11, 0x5a, 0x75, 0x1f, 0x5a, 0xd2, 0x35, 0x71, 0xfe,
	0x88, 0x60, 0x73, 0x9a, 0xce, 0x17, 0x56, 0xc6, 0xab, 0x2a, 0x34, 0xd6, 0xe0, 0x1a, 0x44, 0xb0,
	0x32, 0xca, 0x44, 0x91, 0x96, 0x22, 0x58, 0x44, 0x48, 0x6e, 0x6c, 0x3b, 0x29, 0x46, 0x32, 0xce,
	0xb8, 0x85, 0x7f, 0xd5, 0xd9, 0xde, 0x04, 0x19, 0x67, 0xa2, 0x48, 0xca, 0x69, 0xc3, 0x3d, 0xac,
	0x7c, 0x53, 0x1b, 0x15, 0x7a, 0x26, 0x99, 0x8c, 0x0f, 0x33, 0xc0, 0x03, 0x80, 0x26, 0x47, 0x46,
	0xbf, 0x94, 0xf2, 0x2f, 0x8b, 0x8a, 0xb4, 0x7c, 0x23, 0xb9, 0x86, 0xdd, 0x8f, 0xa0, 0x33, 0x79,
	0xaf, 0x6a, 0xfa, 0xea, 0x9a, 0x1b, 0xc4, 0xa2, 0x61, 0x69, 0x89, 0x3f, 0x2d, 0xcf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7d, 0x86, 0xba, 0x4f, 0x18, 0x01, 0x00, 0x00,
}
